# -*- coding: utf-8 -*-
"""
db/postgres_client.py — Async PostgreSQL connection pool and query functions

This module owns the single asyncpg connection pool for the entire app.
All database operations are async so they never block the FastAPI event loop.

Tables used (defined in db/schema.sql, auto-created by Docker on first boot):
    users      — registered users with hashed passwords and roles
    query_log  — every RAG query that goes through the API
    feedback   — thumbs up/down ratings on specific answers

Connection string is built from .env variables:
    POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
"""

import json
import os
from typing import Optional

import asyncpg

# ── Connection string ──────────────────────────────────────────────────────────
DATABASE_URL = (
    f"postgresql://{os.getenv('POSTGRES_USER', 'cnst_user')}"
    f":{os.getenv('POSTGRES_PASSWORD', 'devpassword123')}"
    f"@{os.getenv('POSTGRES_HOST', 'localhost')}"
    f":{os.getenv('POSTGRES_PORT', '5432')}"
    f"/{os.getenv('POSTGRES_DB', 'cnst_rag')}"
)

# ── Connection pool singleton ──────────────────────────────────────────────────
_pool: Optional[asyncpg.Pool] = None


async def get_pool() -> asyncpg.Pool:
    """
    Return the shared connection pool, creating it on first call.

    Pool settings:
        min_size=2  — always keep 2 connections open (fast response)
        max_size=10 — max 10 simultaneous queries (enough for demo scale)
        command_timeout=30 — fail loudly instead of hanging forever
    """
    global _pool
    if _pool is None:
        _pool = await asyncpg.create_pool(
            DATABASE_URL,
            min_size=2,
            max_size=10,
            command_timeout=30,
        )
    return _pool


# ══════════════════════════════════════════════════════════════════════════════
# User queries
# ══════════════════════════════════════════════════════════════════════════════

async def get_user_by_email(email: str) -> Optional[asyncpg.Record]:
    """
    Fetch a user row by email address.
    Returns None if the user doesn't exist or is inactive.
    """
    pool = await get_pool()
    return await pool.fetchrow(
        "SELECT id, email, role, password_hash FROM users WHERE email=$1 AND is_active=true",
        email,
    )


async def update_last_login(user_id: str) -> None:
    """Update the last_login timestamp when a user successfully logs in."""
    pool = await get_pool()
    await pool.execute(
        "UPDATE users SET last_login = NOW() WHERE id=$1",
        user_id,
    )


# ══════════════════════════════════════════════════════════════════════════════
# Query logging
# ══════════════════════════════════════════════════════════════════════════════

async def log_query(
    query_id:     str,
    session_id:   str,
    user_id:      Optional[str],
    user_role:    str,
    query:        str,
    answer:       str,
    sources:      list,
    confidence:   float,
    retrieval_ms: int,
    generation_ms: int,
    total_ms:     int,
    cache_hit:    bool,
    llm_backend:  str,
    llm_model:    str,
) -> None:
    """
    Insert a completed RAG query into the query_log table.

    query_id is pre-generated by the API endpoint so it can be returned
    in the response immediately (before this background task runs).
    Called as a FastAPI BackgroundTask so it never blocks the response.
    """
    pool = await get_pool()
    await pool.execute(
        """
        INSERT INTO query_log (
            id, session_id, user_id, user_role, query, answer, sources,
            confidence, retrieval_ms, generation_ms, total_ms,
            cache_hit, llm_backend, llm_model
        )
        VALUES ($1::uuid, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, $10, $11, $12, $13, $14)
        ON CONFLICT (id) DO NOTHING
        """,
        query_id,
        session_id,
        user_id if user_id != "anonymous" else None,
        user_role,
        query,
        answer,
        json.dumps(sources),
        confidence,
        retrieval_ms,
        generation_ms,
        total_ms,
        cache_hit,
        llm_backend,
        llm_model,
    )



# ══════════════════════════════════════════════════════════════════════════════
# Feedback
# ══════════════════════════════════════════════════════════════════════════════

async def record_feedback(query_id: str, rating: int, comment: str = "") -> None:
    """
    Record a thumbs up (+1) or thumbs down (-1) rating for a specific answer.

    Args:
        query_id: UUID of the query_log row being rated
        rating:   +1 (helpful) or -1 (not helpful)
        comment:  Optional text comment from the user
    """
    pool = await get_pool()
    await pool.execute(
        "INSERT INTO feedback (query_id, rating, comment) VALUES ($1, $2, $3)",
        query_id,
        rating,
        comment,
    )


async def get_feedback_stats() -> dict:
    """
    Return aggregate satisfaction statistics across all feedback.

    Returns:
        {
            "total":            int   — total ratings submitted
            "positive":         int   — thumbs up count
            "satisfaction_pct": float — percentage of positive ratings
        }
    """
    pool = await get_pool()
    row = await pool.fetchrow(
        """
        SELECT
            COUNT(*)                                                    AS total,
            SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END)               AS positive,
            ROUND(AVG(CASE WHEN rating = 1 THEN 100.0 ELSE 0 END), 1) AS satisfaction_pct
        FROM feedback
        """
    )
    return {
        "total":            int(row["total"]),
        "positive":         int(row["positive"] or 0),
        "satisfaction_pct": float(row["satisfaction_pct"] or 0.0),
    }


async def get_recent_queries(limit: int = 20) -> list:
    """
    Return the most recent queries from query_log (for admin dashboard use).
    """
    pool = await get_pool()
    rows = await pool.fetch(
        """
        SELECT query, answer, total_ms, cache_hit, user_role, created_at
        FROM query_log
        ORDER BY created_at DESC
        LIMIT $1
        """,
        limit,
    )
    return [dict(row) for row in rows]
